# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ce3d37682eb4c951fd664470f1cba111"
name = "[staging] levis-bxgy"
handle = "staging-levis-bxgy"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "cod-app-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
